yesterday i spent 4 hours in this bug

```typescript
export const verifyJwt = (token: string) => {
  try {
    const decoded = jwt.verify(token, config.rsa.publicKey);

    return { payload: decoded, expired: false };
  } catch (error: any) {
	//misspelled i was just missing an s in includes
    return { payload: null, expired: error.message.include('jwt expired') };
	//corrent way
    //return { payload: null, expired: error.message.includes('jwt expired') };
  }
};
```